### ISSUE TITLE
Install Laravel 8.0

### ISSUE THREAD

**Issue by sergiomsa** [grayloon/magento-laravel-api#37]
Using version ^0.4.1 for grayloon/laravel-magento-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - Can only install one of: guzzlehttp/guzzle[7.1.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.1.1].
    - grayloon/laravel-magento-api 0.4.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for grayloon/laravel-magento-api ^0.4.1 -> satisfiable by grayloon/laravel-magento-api[0.4.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.1.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.1.1].

**Comment by ahinkle** [comment]
Thanks! This was fixed recently. I just published a version (0.5.0) that should resolve this issue.

**Comment by sergiomsa** [comment]
Thks. Fantastic.
