### ISSUE TITLE
Filtering data 

### ISSUE THREAD

**Issue by CovertError** [grayloon/magento-laravel-api#51]
`        $response = $magento->api('orders')->all($pageSize = 1, $currentPage = 1, $filters = ["created_at&searchCriteria[filter_groups][0][filters][0][value]=2016-07-01 00:00:00"]);
`
so i have tried almost everything I can think of to filter the data would you please explain the right way thanks

**Comment by ahinkle** [comment]
Hi, please refer to the [Magento Swagger Documentation](https://devdocs.magento.com/redoc/2.2/#tag/orders).

In your case you would use something similar:

```php

$response = $magento->api('orders')->all($pageSize = 1, $currentPage = 1, $filters = [
    'searchCriteria[filterGroups][0][filters][0][field]' => 'created_at',
    'searchCriteria[filterGroups][0][filters][0][value]' => '2016-07-01 00:00:00',
]);
```

This would return an order with exactly the `created_at` timestamp of `2016-07-01 00:00:00`. 

To test your query, you can try your local Magento swagger

**Comment by CovertError** [comment]
thank you so much for your reply that really helps another issue I have been trying to solve is to reach the value corresponding to the postcode in my case post code is under extension_attributes -> shipping_assignments -> shipping -> address

      "extension_attributes" => array:5 [▼
        "shipping_assignments" => array:1 [▼
          0 => array:2 [▼
            "shipping" => array:3 [▼
              "address" => array:13 [▼
                "address_type" => "shipping"
                "city" => "test"
                "country_id" => "US"
                "email" => "test@test.com"
                "entity_id" => 92
                "firstname" => "test"
                "lastname" => "test"
                "parent_id" => 47
                "postcode" => "12345"
