### ISSUE TITLE
Improve Documentation Readability

### ISSUE THREAD

**Issue by ahinkle** [grayloon/magento-laravel-api#55]
As the project grew, the documentation got a bit messy. The idea here would be to add a `<dataset>` for each endpoint with an index to quickly navigate to the endpoint at the top of the readme.

**Comment by akabakass** [comment]
Hey, glad to start helping here been assigned via code relay.io) but I'm not sure I understand the need here, can you detail a little more please?

**Comment by ahinkle** [comment]
Hey @akabakass ,

Thanks for looking into this. So, the [Available Methods](https://github.com/grayloon/magento-laravel-api#available-methods) section is quite messy and I was thinking we could clean this up by usage of a table or other means to make things more uniform . Feel free to submit your own ideas 👍
