### ISSUE TITLE
Add a nopages method for Orders?

### ISSUE THREAD

**Issue by rickjm540** [grayloon/magento-laravel-api#60]
Could we add a function similar to:

public function all_nopages($filters = [])
    {
        return $this->get('/orders',$filters);
    }

to the Api/Orders class?

I'd like to get the raw data :)

**Comment by ahinkle** [comment]
Hi @rickjm540 ,

You can extend the class in your application for that method. We currently don't have plans to support that in this package.

With Products, Orders, Categories, and more you run the risk of having memory issues if you do not paginate the results. We give the option to set the pagination in large data sets. Alternatively, you can set the results to display the first 1000, which is the Magento limit.

Thanks!

**Comment by rickjm540** [comment]
Perfect - Thanks much!
