### ISSUE TITLE
SKU with slash

### ISSUE THREAD

**Issue by jeroen-hso** [grayloon/magento-laravel-api#61]
Hi Andy,

How to handle sku's with slashes (/)? Do I have to urlencode all the sku's before using an API endpoint or is there setting for this? Is the urlencoding only needed for the url or also for the Postdata?

Thanks!

**Comment by ahinkle** [comment]
Interesting - haven't come across that before. 

Are you able to access the API endpoint(s) by accessing the API directly? e.g. via curl: `rest/default/V1/products/some-product-with-a/-slash`

I came across this article but it's ages old: https://magento.stackexchange.com/questions/142056/how-to-get-magento2-product-with-rest-if-sku-has-slash

**Comment by jeroen-hso** [comment]
I found the same issue on stackexchange.

This doesn't work:
```
     public function getProduct($sku) { // $sku = '1234/56'
         $result = $this->api('products')->show($sku); 
         if ($result->status() == 200) {
             return $result->json();
     }
```
And this works:
```
     public function getProduct($sku) { // $sku = '1234/56'
         $sku = urlencode($sku);
         $result = $this->api('products')->show($sku); 
         if ($result->status() == 200) {
             return $result->json();
     }

```

**Comment by ahinkle** [comment]
@jeroen-hso ,

Are there any problems with URL encoding as the default on SKUs? I'm open to the idea if not :)

**Comment by jeroen-hso** [comment]
@ahinkle sorry for the late reply. I don't think there are any problems when the URL for SKU is default encoded. But I'm not a expert on this.

**Comment by jeroen-hso** [comment]
@ahinkle just found out one problem, when the SKU contains a space URL encoding changes the space to + (I don't understand why suppliers create SKU's with spaces)

**Comment by ahinkle** [comment]
Yeah, good point. I think for now I'll keep the current implementation and leave it up to the users to pass it how they would like in their own applications. Just feels a bit finicky and could break some applications.
