### ISSUE TITLE
oauth support

### ISSUE THREAD

**Issue by medspec** [grayloon/magento-laravel-api#86]
i am trying to make call using the "access token" but keep getting the error that i dont have access to the resources.

i see in the magento manual that a connection using only the token is disables by default
https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html

but there "fix" to enable "enable_integration_as_bearer" is also no good, that has also been removed. 
they continue to imply we should us oauth, is that supported?

**Comment by ahinkle** [comment]
Hey there,

There are no plans for OAuth as this package is native to [Laravel's HTTP Client](https://laravel.com/docs/9.x/http-client).  Feel free to fork your own version though!

Thanks!

**Comment by ahinkle** [comment]
Hey @medspec,

I found this workaround (not ideal) but it should get you working for now.
