### ISSUE TITLE
laravel 9 support

### ISSUE THREAD

**Issue by CovertError** [grayloon/magento-laravel-api#89]
I'm having an issue updating to laravel 9  
Problem 1
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.6) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.6) does not satisfy that requirement.
    - Root composer.json requires grayloon/laravel-magento-api ^0.9.0 -> satisfiable by grayloon/laravel-magento-api[0.9.0, 0.9.1].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.1.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.6.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.7.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.8.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.9.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.10.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.10.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.11.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.12.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.14.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.19.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.21.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.22.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - grayloon/laravel-magento-api[0.9.0, ..., 0.9.1] require illuminate/support ^7.0|^8.0 -> satisfiable by illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

**Comment by ahinkle** [comment]
Hi there. 

You are attempting to install v0.9. Update to v0.15 for Laravel 9. 

https://github.com/grayloon/magento-laravel-api/releases/tag/0.15.0
